import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { CalendarDays, Check, ChevronRight, LogOut, Save, UserRound } from 'lucide-react';
import { ButtonLink, Layout, PageIntro } from '@/components/layout';
import { Field, SelectField } from '@/components/ui';
import { accountService } from '@/services/accountService';
import { atendimentosService } from '@/services/atendimentosService';
import { organizacoesService } from '@/services/organizacoesService';
import type { Atendimento, Area, Modalidade, Organizacao, Usuario } from '@/types';

function AccountFrame({ children, title, step }: { children: ReactNode; title: string; step?: string }) {
  return <Layout minimal><div className="min-h-[calc(100dvh-72px)] bg-[#e6eee7] py-10 md:py-16"><div className="shell max-w-2xl">{step && <p className="eyebrow text-secondary-foreground">{step}</p>}<h1 className="mt-3 font-serif text-4xl font-extrabold leading-tight tracking-[-.06em] text-primary md:text-5xl">{title}</h1><div className="mt-8 rounded-2xl border border-border bg-card p-5 shadow-sm md:p-8">{children}</div></div></div></Layout>;
}

export function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const navigate = useNavigate();
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!email || !password) { setError('Preencha seu e-mail e sua senha para continuar.'); return; } await accountService.login(email); navigate('/account/dashboard/psicologia/agenda'); };
  return <AccountFrame title="Que bom ver você por aqui." step="Acessar o FortClinic"><form onSubmit={submit} className="grid gap-5"><Field label="Seu e-mail" type="email" placeholder="voce@email.com" value={email} onChange={(e) => setEmail(e.target.value)} name="email" /><Field label="Senha" type="password" placeholder="••••••••" value={password} onChange={(e) => setPassword(e.target.value)} name="password" />{error && <p className="rounded-xl bg-[#f6ded8] p-3 text-sm font-semibold text-primary">{error}</p>}<button type="submit" className="mt-2 flex h-12 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground" data-testid="button-login-submit">Entrar</button><div className="flex flex-col gap-3 pt-2 text-center text-sm"><button type="button" className="font-semibold text-secondary-foreground" onClick={() => setError('Em breve você poderá recuperar sua senha por aqui.')} data-testid="button-forgot-password">Esqueci minha senha</button><span className="text-muted-foreground">Ainda não tem conta? <Link to="/account/cadastro" className="font-bold text-primary" data-testid="link-signup">Criar cadastro</Link></span></div></form></AccountFrame>;
}

export function CadastroPage() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [type, setType] = useState<Usuario['tipo']>('cliente'); const [done, setDone] = useState(false); const navigate = useNavigate();
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name || !email) return; await accountService.cadastro(name, email, type); setDone(true); };
  if (done) return <AccountFrame title="Cadastro criado." step="Tudo pronto"><div className="grid place-items-center py-6 text-center"><div className="grid size-14 place-items-center rounded-full bg-secondary text-secondary-foreground"><Check /></div><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">Agora você pode explorar a rede ou começar a apresentar o seu trabalho.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><ButtonLink to={type === 'profissional' ? '/account/comecar-perfil' : '/busca'}>{type === 'profissional' ? 'Criar meu perfil' : 'Buscar atendimento'}</ButtonLink></div></div></AccountFrame>;
  return <AccountFrame title="Comece por aqui." step="Criar uma conta"><form onSubmit={submit} className="grid gap-5"><Field label="Como podemos chamar você?" type="text" placeholder="Seu nome" value={name} onChange={(e) => setName(e.target.value)} name="name" /><Field label="Seu e-mail" type="email" placeholder="voce@email.com" value={email} onChange={(e) => setEmail(e.target.value)} name="email" /><label className="grid gap-2 text-sm font-bold">Quero usar o FortClinic para<select value={type} onChange={(e) => setType(e.target.value as Usuario['tipo'])} className="h-12 rounded-xl border border-input bg-card px-4 font-normal" data-testid="select-account-type"><option value="cliente">Encontrar atendimento</option><option value="profissional">Oferecer atendimento</option></select></label><label className="flex items-start gap-3 text-xs leading-5 text-muted-foreground"><input type="checkbox" required className="mt-1 accent-primary" data-testid="checkbox-terms" />Li e concordo com os <Link to="/doc/politicas-de-uso" className="font-bold text-primary">termos de uso</Link>.</label><button type="submit" className="h-12 rounded-full bg-primary text-sm font-bold text-primary-foreground" data-testid="button-signup-submit">Criar minha conta</button><p className="text-center text-sm text-muted-foreground">Já tem uma conta? <Link to="/account/login" className="font-bold text-primary">Entrar</Link></p></form></AccountFrame>;
}

export function OnboardingPage() {
  return <AccountFrame title="Vamos apresentar o seu cuidado." step="01 / 02 · Para profissionais e organizações"><div className="grid gap-4"><div className="rounded-2xl bg-secondary p-5"><p className="font-serif text-xl font-bold text-primary">Seu trabalho merece ser encontrado.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Vamos pedir só o essencial: quem você atende, onde e como as pessoas podem chegar.</p></div><div className="grid gap-3"><OnboardItem number="01" title="Informações básicas" /><OnboardItem number="02" title="Horários e contato" /></div><ButtonLink to="/account/profissional/criar">Começar meu perfil</ButtonLink></div></AccountFrame>;
}
function OnboardItem({ number, title }: { number: string; title: string }) { return <div className="flex items-center gap-4 rounded-xl border border-border p-4"><span className="font-mono text-xs font-bold text-secondary-foreground">{number}</span><span className="font-semibold">{title}</span><ChevronRight className="ml-auto text-muted-foreground" size={17} /></div>; }

export function ProfessionalCreatePage() {
  const navigate = useNavigate(); const [name, setName] = useState(''); const [area, setArea] = useState('psicologia'); const [mode, setMode] = useState('online'); const [region, setRegion] = useState('Aldeota'); const [description, setDescription] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); const created = await organizacoesService.criar({ nome: name || 'Meu perfil', area: area as Area, modalidade: mode as Modalidade, regiao: region, descricao: description || 'Atendimento acolhedor e acessível para a comunidade.' }); navigate(`/perfil/${created.id}`); };
  return <AccountFrame title="Conte um pouco sobre o seu trabalho." step="02 / 02 · Criar perfil"><form onSubmit={submit} className="grid gap-5"><Field label="Nome público" hint="Pode ser seu nome, clínica ou projeto." value={name} onChange={(e) => setName(e.target.value)} placeholder="Ex.: Espaço Recomeço" name="public-name" /><SelectField label="Área de atuação" value={area} onChange={setArea} options={[{ value: 'psicologia', label: 'Psicologia' }, { value: 'advocacia', label: 'Advocacia' }, { value: 'medicina', label: 'Medicina' }, { value: 'outro', label: 'Outro' }]} /><SelectField label="Modalidade" value={mode} onChange={setMode} options={[{ value: 'online', label: 'Online' }, { value: 'presencial', label: 'Presencial' }, { value: 'ambos', label: 'Online e presencial' }]} /><SelectField label="Região" value={region} onChange={setRegion} options={[{ value: 'Aldeota', label: 'Aldeota' }, { value: 'Centro', label: 'Centro' }, { value: 'Messejana', label: 'Messejana' }, { value: 'Bom Jardim', label: 'Bom Jardim' }, { value: 'Parangaba', label: 'Parangaba' }]} /><label className="grid gap-2 text-sm font-bold">Como você pode ajudar?<textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Fale de forma simples sobre o atendimento…" className="min-h-32 resize-y rounded-xl border border-input bg-card p-4 font-normal outline-none focus:border-ring" data-testid="textarea-description" /></label><button type="submit" className="flex h-12 items-center justify-center gap-2 rounded-full bg-primary text-sm font-bold text-primary-foreground" data-testid="button-create-profile"><Save size={17} />Publicar perfil</button></form></AccountFrame>;
}

export function ManagePage() {
  const [saved, setSaved] = useState(false);
  return <Layout><PageIntro eyebrow="Minha presença" title="Gerencie seu perfil público." description="Mantenha as informações que ajudam as pessoas a escolherem o cuidado certo."><div className="mt-8 flex flex-wrap gap-3"><ButtonLink to="/account/profissional/criar" secondary>Editar informações</ButtonLink><ButtonLink to="/account/dashboard/psicologia/agenda">Ver meu painel</ButtonLink></div></PageIntro><section className="shell grid gap-5 py-10 md:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-border bg-card p-6"><div className="flex items-start justify-between"><div><p className="eyebrow text-secondary-foreground">Perfil ativo</p><h2 className="mt-2 font-serif text-2xl font-bold">Ponte de Escuta</h2><p className="mt-1 text-sm text-muted-foreground">Psicologia · Online</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground">Publicado</span></div><div className="mt-6 grid gap-3 text-sm"><div className="flex justify-between border-t border-border pt-3"><span className="text-muted-foreground">Região</span><strong>Aldeota</strong></div><div className="flex justify-between border-t border-border pt-3"><span className="text-muted-foreground">Horários</span><strong>2 dias por semana</strong></div></div></div><div className="rounded-2xl bg-[#f4e9bd] p-6 text-primary"><p className="eyebrow">Dica FortClinic</p><h2 className="mt-3 font-serif text-2xl font-bold">Um perfil claro acolhe antes mesmo do primeiro contato.</h2><p className="mt-3 text-sm leading-6 text-primary/70">Conte para quem seu trabalho é indicado e revise seus horários com frequência.</p><button type="button" onClick={() => setSaved(true)} className="mt-5 rounded-full bg-primary px-4 py-2 text-xs font-bold text-primary-foreground" data-testid="button-manage-save">{saved ? 'Lembrete salvo' : 'Entendi'}</button></div></section></Layout>;
}

export function ConfigPage() {
  const { secao = 'perfil' } = useParams(); const [name, setName] = useState('Marina Souza'); const [saved, setSaved] = useState(false);
  const title: Record<string, string> = { perfil: 'Seu perfil', notificacoes: 'Notificações', seguranca: 'Segurança' };
  return <Layout><PageIntro eyebrow="Conta / configurações" title={title[secao] ?? 'Configurações'} description="Cuide dos seus dados e preferências no FortClinic." /><section className="shell grid gap-8 py-10 md:grid-cols-[220px_1fr]"><aside className="flex gap-2 overflow-auto md:grid md:content-start"><ConfigNav section="perfil" current={secao} /><ConfigNav section="notificacoes" current={secao} /><ConfigNav section="seguranca" current={secao} /></aside><div className="rounded-2xl border border-border bg-card p-6">{secao === 'perfil' && <form onSubmit={(e) => { e.preventDefault(); setSaved(true); }} className="grid max-w-lg gap-5"><Field label="Nome" value={name} onChange={(e) => setName(e.target.value)} name="account-name" /><Field label="E-mail" value="marina@email.com" name="account-email" /><button className="h-11 rounded-full bg-primary px-5 text-sm font-bold text-primary-foreground" data-testid="button-save-account">{saved ? 'Alterações salvas' : 'Salvar alterações'}</button></form>}{secao === 'notificacoes' && <div className="grid gap-5"><Toggle title="Lembretes de agendamento" text="Receba um aviso antes dos seus atendimentos." /><Toggle title="Novidades da rede" text="Saiba quando surgirem novos serviços perto de você." /></div>}{secao === 'seguranca' && <div className="max-w-lg"><p className="text-sm leading-6 text-muted-foreground">Sua conta está protegida. A autenticação real será conectada na próxima etapa do produto.</p><button type="button" onClick={() => accountService.logout()} className="mt-6 flex items-center gap-2 rounded-full border border-destructive/30 px-4 py-2 text-sm font-bold text-destructive" data-testid="button-logout"><LogOut size={16} />Sair da conta</button></div>}</div></section></Layout>;
}
function ConfigNav({ section, current }: { section: string; current: string }) { return <Link to={`/account/config/${section}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold capitalize md:rounded-xl ${current === section ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`} data-testid={`link-config-${section}`}>{section}</Link>; }
function Toggle({ title, text }: { title: string; text: string }) { const [on, setOn] = useState(true); return <button type="button" onClick={() => setOn(!on)} className="flex items-center justify-between gap-4 border-b border-border pb-5 text-left" data-testid={`button-toggle-${title}`}><span><strong className="block text-sm">{title}</strong><small className="mt-1 block text-xs leading-5 text-muted-foreground">{text}</small></span><span className={`flex h-6 w-11 items-center rounded-full p-1 transition-colors ${on ? 'bg-secondary-foreground' : 'bg-muted'}`}><span className={`size-4 rounded-full bg-card transition-transform ${on ? 'translate-x-5' : ''}`} /></span></button>; }

export function DashboardPage() {
  const { tipo = 'psicologia', secao = 'agenda' } = useParams(); const [items, setItems] = useState<Atendimento[]>([]); const [status, setStatus] = useState(''); const [org, setOrg] = useState<Organizacao>();
  useEffect(() => { atendimentosService.listar().then(setItems); organizacoesService.buscarPorId('ponte-escuta').then(setOrg); }, []);
  const upcoming = items.filter((item) => item.status === 'reservado'); const history = items.filter((item) => item.status === 'concluido');
  const displayItems = secao === 'historico' ? history : upcoming;
  const markDone = async (id: string) => { await atendimentosService.atualizarStatus(id, 'concluido'); setItems((old) => old.map((item) => item.id === id ? { ...item, status: 'concluido' } : item)); setStatus('Atendimento atualizado'); };
  return <Layout><PageIntro eyebrow={`Painel · ${tipo}`} title={secao === 'historico' ? 'O que já foi cuidado.' : 'Sua semana, em um só lugar.'} description="Acompanhe os próximos atendimentos e mantenha sua agenda viva."><div className="mt-8 flex gap-2 overflow-auto"><DashNav type={tipo} section="agenda" /><DashNav type={tipo} section="historico" /></div></PageIntro><section className="shell py-8"><div className="grid gap-4 sm:grid-cols-3"><Stat label="Próximos atendimentos" value={String(upcoming.length)} icon={<CalendarDays size={18} />} /><Stat label="Atendimentos concluídos" value={String(history.length)} icon={<Check size={18} />} /><Stat label="Perfil" value={org?.nome ?? 'Ponte de Escuta'} icon={<UserRound size={18} />} /></div><div className="mt-8 rounded-2xl border border-border bg-card p-5 md:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow text-secondary-foreground">{secao === 'historico' ? 'Histórico' : 'Agenda'}</p><h2 className="mt-2 font-serif text-2xl font-bold">{secao === 'historico' ? 'Atendimentos finalizados' : 'Próximos encontros'}</h2></div><Link to="/account/profissional/gerenciar" className="flex items-center gap-1 text-sm font-bold text-secondary-foreground" data-testid="link-dashboard-manage">Gerenciar perfil <ChevronRight size={16} /></Link></div>{status && <p className="mt-4 rounded-lg bg-secondary p-3 text-sm font-bold text-secondary-foreground">{status}</p>}{displayItems.length ? <div className="mt-6 grid gap-3">{displayItems.map((item) => <div key={item.id} className="flex flex-col gap-4 rounded-xl border border-border p-4 sm:flex-row sm:items-center"><div className="grid size-11 place-items-center rounded-xl bg-[#f4e9bd] text-primary"><CalendarDays size={19} /></div><div className="flex-1"><p className="font-bold">{item.nomePessoa ?? 'Pessoa atendida'}</p><p className="mt-1 text-xs text-muted-foreground">{item.data} · {item.horario} · {item.modalidade}</p></div>{item.status === 'reservado' && <button type="button" onClick={() => markDone(item.id)} className="rounded-full border border-secondary-foreground/30 px-4 py-2 text-xs font-bold text-secondary-foreground" data-testid={`button-complete-${item.id}`}>Marcar concluído</button>}<span className="text-xs font-bold capitalize text-muted-foreground">{item.status}</span></div>)}</div> : <p className="mt-8 rounded-xl bg-muted p-6 text-sm text-muted-foreground">Nenhum atendimento nesta seção ainda.</p>}</div></section></Layout>;
}
function DashNav({ type, section }: { type: string; section: string }) { return <Link to={`/account/dashboard/${type}/${section}`} className="rounded-full bg-secondary px-4 py-2 text-xs font-bold capitalize text-secondary-foreground" data-testid={`link-dashboard-${section}`}>{section}</Link>; }
function Stat({ label, value, icon }: { label: string; value: string; icon: ReactNode }) { return <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between text-secondary-foreground">{icon}<span className="font-mono text-2xl font-bold text-primary">{value}</span></div><p className="mt-5 text-xs font-semibold leading-5 text-muted-foreground">{label}</p></div>; }

export function FeedbackPage() {
  const [sent, setSent] = useState(false); const [text, setText] = useState(''); const [rating, setRating] = useState(0);
  if (sent) return <Layout><div className="shell py-20"><div className="mx-auto max-w-xl text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-secondary text-secondary-foreground"><Check /></div><h1 className="mt-6 font-serif text-4xl font-extrabold tracking-[-.06em]">Obrigado por construir com a gente.</h1><p className="mt-4 text-muted-foreground">Sua mensagem ajuda o FortClinic a ficar mais próximo de quem precisa.</p><div className="mt-8"><ButtonLink to="/">Voltar para o início</ButtonLink></div></div></div></Layout>;
  return <Layout><PageIntro eyebrow="A gente quer ouvir" title="Como foi sua experiência?" description="Pode ser uma ideia, um elogio ou algo que não funcionou bem. Toda mensagem é bem-vinda." /><section className="shell py-10"><form onSubmit={(e) => { e.preventDefault(); setSent(true); }} className="max-w-2xl rounded-2xl border border-border bg-card p-6 md:p-8"><label className="grid gap-3 text-sm font-bold">Como você se sentiu usando o FortClinic?<div className="flex gap-2">{[1, 2, 3, 4, 5].map((item) => <button type="button" key={item} onClick={() => setRating(item)} className={`grid size-11 place-items-center rounded-xl border text-lg transition-colors ${rating >= item ? 'border-accent bg-accent text-primary' : 'border-border text-muted-foreground'}`} aria-label={`${item} de 5`} data-testid={`button-rating-${item}`}>{item}</button>)}</div></label><label className="mt-7 grid gap-2 text-sm font-bold">Conte mais, se quiser<textarea value={text} onChange={(e) => setText(e.target.value)} className="min-h-36 rounded-xl border border-input bg-background p-4 font-normal outline-none focus:border-ring" placeholder="Escreva sua mensagem…" data-testid="textarea-feedback" /></label><button type="submit" className="mt-6 rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground" data-testid="button-submit-feedback">Enviar feedback</button></form></section></Layout>;
}